### PR TITLE
Minor refactorization of the code and little improvements

### PR DESCRIPTION
**Pull request by ignabelitzky**
This is some of the things I modified:

- Better restructuration of the directories and little refactorization of the code.
- .gitignore added.
- Makefile created so it's easier to compile the program.
- Destructor implementation for the EmployeeManagement Class

If you got doubts about the refactorization please leave a comment.
Hope you can approve the PR

### CODE REVIEW

**Comment by khanshaib11** [comment]
Great

**Comment by ignabelitzky** [comment]
> Great

Sorry, today I deleted the fork... anyways the changes are in the "files changed" tab if you wanna take a look.
I think I will try to make the Pull Request again so you can merge the changes if you want.

**Comment by khanshaib11** [comment]
I am sorry that u gave your time , i am slowly learning the github and its option . Can u tell me how i can add the changes u  made ? and can u also add changes by yourself without my permission?

**Comment by ignabelitzky** [comment]
> I am sorry that u gave your time , i am slowly learning the github and its option . Can u tell me how i can add the changes u made ? and can u also add changes by yourself without my permission?

I can't directly change your repository, if you've got your repo public as you do, I can fork it and make some changes, then I can open a Pull Request with the changes, but you can accept it or not, it's up to you at the end.

I will open a new Pull Request so you can see the changes and decide.

**Pull request closed without merging**
